<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
 <div id="bor"> <title>Le Biocoin</title>
  <link rel="stylesheet" href="accueil.css">
<div id=fond><body>
 <CENTER><div id="co"> <div></CENTER>
  <div id="ligne2"><h></div>
 <div id="forme">
<div id="hautdepage"><p>Je me connecte Je m'inscris</p></div>

<p><p1>Le Biocoin</p1>
  <div id="logo"><img src="logo1.png"></img></div>
 <h3> Site de ventes de fruits & légumes</h3>

 <div id="pos"> <img src="fruits.jpg"></img></div>
    <nav>


        <ul><b>
          <li>ACCUEIL</li>
          <li>LEGUMES</li>
          <li>FRUITS</li>
          <li>LABEL BIO</li>
          <li>RECETTES</li>
          <li>FORUM</li>
          </b>
        </ul>
      </nav>

<div id="contenuaccueil"><p><h4> LE CONCEPT</h4></p>
<img width="229" height="200" align="right" alt="pomme" src="po.jpg"></img>
<p>LEBIOCOIN est un site d’échange et de ventes de fruits et légumes frais.</p>
<p>Il a pour but de : </p>
<p>-redonner de l’importance et de la valeur aux fruits et légumes </p> 
<p>-privilégier la qualité et fraicheur des produits. Mais comment ? </p>
<p>L’achat ou l’échange s’effectue entre deux producteurs à proximité </p>
<p> Le nombre de kilomètre parcourus par les produits étant réduits,</p>
<p> leur fraicheur et qualité en sera meilleur.</p>

<h4>LE PANIER</h4>
<img width="229" height="200" align="right" alt="pomme" src="livraison.jpg"></img>
<p> LE BIOCOIN s’occupe <u>gratuitement</u> de la livraison de votre panier:
 -directement chez vous.</p>
<p>-sur votre lieu de vacances. </p>
</div>


<div id=page>
 
 <div id="posi"> <img src="icone.jpg"></img></div>
  <div id="posi2"> <img src="panier.jpg"></img></div>
  <div id="menu"></div>
</div>
<div id="h"></div>
<div id="gauche">

</div>


<div id="recherche">
<input type="texte" name="recherche" value="Je recherche..."/>
<input type="submit" value="OK"/> 
</div>
<b>
<ul> 
  <div id="bordureg">

<li>  Annonces échanges </li> <br><br>
<li>  Annonces Ventes </li><br><br>
<li>  Je crée mon annonce </li> <br><br>
<li> Mentions legales</li><br><br>
<li>  Aide </li> 
</ul>
</b>
</div>
<div id="newsletter"><h4><u>LA NEWSLETTER</u></h4>
<p><input type="text" name="pseudo" value="rentrer votre mail" /> </p>
 <p><INPUT TYPE="submit" NAME="Valider" VALUE=" Envoyer"></p>

</div>

<div id="mag"><h4><u>LA REVUE</u></h4>
  <img src="mag.png"></img>

 <p><input type="text" name="pseudo" value="rentrer votre mail" /> </p>
 <p><INPUT TYPE="submit" NAME="Valider" VALUE=" Envoyer"></p>
 
 <div id="liste">


</div>


</div> 
</body>
</div>
</div>
</html>

